[package]
name = "nota"
version = "0.1.0"
edition = "2021"
authors = ["Salus"]
license = "GPL-3.0 license"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
dirs = "5.0.1"
ratatui = "0.28.0"
thiserror = "1.0.63"
