[package]
name = "literae-meus"
version = "0.1.0"
edition = "2021"
authors = ["Salus"]
license = "GPL-3.0 license"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
genpdf = "0.2.0"
regex = "1.10.5"
thiserror = "1.0.63"
